# Generated by Django 6.0.7 on 2026-07-13 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Selecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Seleção',
                'verbose_name_plural': 'Seleções',
            },
        ),
        migrations.CreateModel(
            name='Figurinha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_jogador', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
                ('posicao', models.CharField(blank=True, max_length=50, null=True)),
                ('eh_rara', models.BooleanField(default=False)),
                ('selecao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='figurinhas', to='album.selecao')),
            ],
            options={
                'ordering': ['selecao', 'numero'],
                'unique_together': {('selecao', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='AlbumUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('eh_repetida', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album', to=settings.AUTH_USER_MODEL)),
                ('figurinha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colecionadores', to='album.figurinha')),
            ],
            options={
                'verbose_name': 'Figurinha do Usuário',
                'verbose_name_plural': 'Abuns dos Usuários',
                'unique_together': {('usuario', 'figurinha')},
            },
        ),
    ]
